// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace jwtOigaSln.Migrations
{
    [DbContext(typeof(OigaContext))]
    [Migration("20220429160627_SeedUsersTable2")]
    partial class SeedUsersTable2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Alejandro",
                            LastName = "Moncada",
                            UserName = "Alejo0921"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Carolina",
                            LastName = "Gahona",
                            UserName = "CGahona"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Santiago",
                            LastName = "Castaño",
                            UserName = "alejoS"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Alejo",
                            LastName = "Monsalve",
                            UserName = "Monsa13"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "David",
                            LastName = "Alejandro",
                            UserName = "Cada123"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Alejo1",
                            LastName = "absd",
                            UserName = "absd"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Alejo2",
                            LastName = "absd",
                            UserName = "absd"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "absd",
                            LastName = "Alejo3",
                            UserName = "absd"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "absd",
                            LastName = "absd",
                            UserName = "Alejo4"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Alejo5",
                            LastName = "absd",
                            UserName = "absd"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "absd",
                            LastName = "Alejo6",
                            UserName = "absd"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "absd",
                            LastName = "absd",
                            UserName = "Alejo7"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Alejo8",
                            LastName = "absd",
                            UserName = "absd"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "absd",
                            LastName = "Alejo9",
                            UserName = "absd"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
